### ISSUE TITLE
[Question] Rules of hooks

### ISSUE THREAD

**Issue by kapral18** [yuchi/react-use-refs#1]
I see that this is getting popularity and I would think that this is an awesome idea too
if not for breaking the rules of hooks.

Can you share why do you think this is safe to use regardless?

Thanks

**Comment by donavon** [comment]
Because it is a fixed number of calls to `useRef` on every render. The rules of hooks are there to make sure you call hooks non-conditionally and in the same order. 

This will **always** call `useRef` three times.

```ts
const [x, y, y] = useRefs();
```

**Comment by yuchi** [comment]
I tried to give a complete, yet minimal, answer in the [FAQ section in the README](https://github.com/yuchi/react-use-refs#frequently-asked-questions). Please @kapral18 have a look and reopen the issue if this does not solve your doubts.
